
version: '3'
services:
  odoo:
    image: odoo:13.0
    container_name: "odoo-webapp"
    hostname: "odoo-webapp"
    links:
      - "postgres:odoo-postgres"
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
  postgres:
    image: postgres
    container_name: "odoo-postgres"
    hostname: "odoo-postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
